Repository codestates-seb/seb39_main_001, pull requests merged in 2022-09, with the labels that each got.

#28 rest api documenation을 위한 stub 작업
  server/juse/build.gradle
  server/juse/src/main/java/com/example/juse/answer/controller/AnswerController.java
  server/juse/src/main/java/com/example/juse/answer/dto/AnswerRequestDto.java
  server/juse/src/main/java/com/example/juse/answer/dto/AnswerResponseDto.java
  server/juse/src/main/java/com/example/juse/answer/mapper/AnswerMapper.java
  server/juse/src/main/java/com/example/juse/answer/repository/AnswerRepository.java
  server/juse/src/main/java/com/example/juse/answer/service/AnswerService.java
  server/juse/src/main/java/com/example/juse/answer/service/AnswerServiceStub.java
  server/juse/src/main/java/com/example/juse/application/controller/ApplicationController.java
  server/juse/src/main/java/com/example/juse/application/dto/ApplicationRequestDto.java
  server/juse/src/main/java/com/example/juse/application/dto/ApplicationResponseDto.java
  server/juse/src/main/java/com/example/juse/application/entity/Application.java
  server/juse/src/main/java/com/example/juse/application/mapper/ApplicationMapper.java
  server/juse/src/main/java/com/example/juse/application/service/ApplicationService.java
  server/juse/src/main/java/com/example/juse/application/service/ApplicationServiceStub.java
  server/juse/src/main/java/com/example/juse/board/controller/BoardController.java
  server/juse/src/main/java/com/example/juse/board/dto/BoardRequestDto.java
  server/juse/src/main/java/com/example/juse/board/dto/BoardResponseDto.java
  server/juse/src/main/java/com/example/juse/board/entity/Board.java
  server/juse/src/main/java/com/example/juse/board/mapper/BoardMapper.java
  server/juse/src/main/java/com/example/juse/board/repository/BoardRepository.java
  server/juse/src/main/java/com/example/juse/board/service/BoardSerivice.java
  server/juse/src/main/java/com/example/juse/board/service/BoardServiceStub.java
  server/juse/src/main/java/com/example/juse/bookmark/controller/BookmarkController.java
  server/juse/src/main/java/com/example/juse/bookmark/dto/BookmarkRequestDto.java
  server/juse/src/main/java/com/example/juse/bookmark/dto/BookmarkResponseDto.java
  server/juse/src/main/java/com/example/juse/bookmark/mapper/BookmarkMapper.java
  server/juse/src/main/java/com/example/juse/bookmark/repository/BookmarkRepository.java
  server/juse/src/main/java/com/example/juse/bookmark/service/BookmarkService.java
  server/juse/src/main/java/com/example/juse/bookmark/service/BookmarkServiceStub.java
  server/juse/src/main/java/com/example/juse/dto/MultiResponseDto.java
  server/juse/src/main/java/com/example/juse/dto/Pagination.java
  server/juse/src/main/java/com/example/juse/dto/SingleResponseDto.java
  server/juse/src/main/java/com/example/juse/helper/filterings/FilterOptions.java
  server/juse/src/main/java/com/example/juse/helper/stubservice/StubService.java
  server/juse/src/main/java/com/example/juse/like/controller/LikeController.java
  server/juse/src/main/java/com/example/juse/like/dto/LikeResponseDto.java
  server/juse/src/main/java/com/example/juse/like/entity/Like.java
  server/juse/src/main/java/com/example/juse/like/mapper/LikeMapper.java
  server/juse/src/main/java/com/example/juse/like/service/LikeService.java
  server/juse/src/main/java/com/example/juse/like/service/LikeServiceStub.java
  server/juse/src/main/java/com/example/juse/question/controller/QuestionController.java
  server/juse/src/main/java/com/example/juse/question/dto/QuestionRequestDto.java
  server/juse/src/main/java/com/example/juse/question/dto/QuestionResponseDto.java
  server/juse/src/main/java/com/example/juse/question/mapper/QuestionMapper.java
  server/juse/src/main/java/com/example/juse/question/service/QuestionService.java
  server/juse/src/main/java/com/example/juse/question/service/QuestionServiceStub.java
  server/juse/src/main/java/com/example/juse/tag/mapper/TagMapper.java
  server/juse/src/main/java/com/example/juse/user/controller/UserController.java
  server/juse/src/main/java/com/example/juse/user/controller/UserLoginController.java
  server/juse/src/main/java/com/example/juse/user/dto/UserRequestDto.java
  server/juse/src/main/java/com/example/juse/user/dto/UserResponseDto.java
  server/juse/src/main/java/com/example/juse/user/entity/User.java
  server/juse/src/main/java/com/example/juse/user/mapper/UserMapper.java
  server/juse/src/main/java/com/example/juse/user/repository/UserRepository.java
  server/juse/src/main/java/com/example/juse/user/service/UserService.java
  server/juse/src/main/java/com/example/juse/user/service/UserServiceStub.java
  server/juse/src/main/resources/application-test.yaml
Labels: documentation

#57 V1 backend feat 48
  server/juse/src/main/java/com/example/juse/IndexController.java
  server/juse/src/main/java/com/example/juse/answer/dto/AnswerResponseDto.java
  server/juse/src/main/java/com/example/juse/answer/entity/Answer.java
  server/juse/src/main/java/com/example/juse/answer/mapper/AnswerMapper.java
  server/juse/src/main/java/com/example/juse/answer/service/AnswerService.java
  server/juse/src/main/java/com/example/juse/answer/service/AnswerServiceImpl.java
  server/juse/src/main/java/com/example/juse/answer/service/AnswerServiceStub.java
  server/juse/src/main/java/com/example/juse/application/entity/Application.java
  server/juse/src/main/java/com/example/juse/application/repository/ApplicationRepository.java
  server/juse/src/main/java/com/example/juse/audit/Auditing.java
  server/juse/src/main/java/com/example/juse/audit/AuditingConfig.java
  server/juse/src/main/java/com/example/juse/board/dto/BoardResponseDto.java
  server/juse/src/main/java/com/example/juse/board/entity/Board.java
  server/juse/src/main/java/com/example/juse/board/repository/BoardRepository.java
  server/juse/src/main/java/com/example/juse/board/service/BoardServiceImpl.java
  server/juse/src/main/java/com/example/juse/bookmark/service/BookmarkServiceImpl.java
  server/juse/src/main/java/com/example/juse/helper/filterings/ParameterUtils.java
  server/juse/src/main/java/com/example/juse/question/controller/QuestionController.java
  server/juse/src/main/java/com/example/juse/question/dto/QuestionResponseDto.java
  server/juse/src/main/java/com/example/juse/question/entity/Question.java
  server/juse/src/main/java/com/example/juse/question/mapper/QuestionMapper.java
  server/juse/src/main/java/com/example/juse/question/service/QuestionService.java
  server/juse/src/main/java/com/example/juse/question/service/QuestionServiceImpl.java
  server/juse/src/main/java/com/example/juse/question/service/QuestionServiceStub.java
  server/juse/src/main/java/com/example/juse/security/config/oauth/PrincipalDetails.java
  server/juse/src/main/java/com/example/juse/security/config/oauth/PrincipalOauth2UserService.java
  server/juse/src/main/java/com/example/juse/user/dto/UserResponseDto.java
  server/juse/src/main/java/com/example/juse/user/entity/User.java
  server/juse/src/main/resources/application-h2.yaml
Labels: feat, BE

#63 V1 backend feat 52
  server/juse/src/main/java/com/example/juse/application/entity/Application.java
  server/juse/src/main/java/com/example/juse/board/entity/Board.java
  server/juse/src/main/java/com/example/juse/board/repository/BoardRepository.java
  server/juse/src/main/java/com/example/juse/bookmark/entity/Bookmark.java
  server/juse/src/main/java/com/example/juse/bookmark/repository/BookmarkRepository.java
  server/juse/src/main/java/com/example/juse/bookmark/service/BookmarkServiceImpl.java
  server/juse/src/main/java/com/example/juse/helper/filterings/ParameterUtils.java
  server/juse/src/main/java/com/example/juse/security/handler/SuccessHandler.java
  server/juse/src/main/java/com/example/juse/user/controller/UserController.java
  server/juse/src/main/java/com/example/juse/user/entity/User.java
  server/juse/src/main/java/com/example/juse/user/mapper/UserMapper.java
  server/juse/src/main/java/com/example/juse/user/service/UserServiceImpl.java
  server/juse/src/main/resources/application-plain.yaml
  server/juse/src/main/resources/application-real.yaml
  server/juse/src/main/resources/db/mysql/data.sql
Labels: feat, BE

#64 V1 backend feat 58
  server/juse/src/main/java/com/example/juse/board/controller/BoardController.java
  server/juse/src/main/java/com/example/juse/board/dto/BoardResponseDto.java
  server/juse/src/main/java/com/example/juse/board/entity/Board.java
  server/juse/src/main/java/com/example/juse/board/service/BoardServiceImpl.java
  server/juse/src/main/resources/db/h2/data.sql
Labels: feat, BE

#73 V1 backend feat (#60)
  server/juse/src/main/java/com/example/juse/board/controller/BoardController.java
  server/juse/src/main/java/com/example/juse/board/repository/BoardRepository.java
  server/juse/src/main/java/com/example/juse/board/repository/CustomBoardRepository.java
  server/juse/src/main/java/com/example/juse/board/service/BoardServiceImpl.java
  server/juse/src/main/java/com/example/juse/helper/filterings/FilterOptions.java
  server/juse/src/main/java/com/example/juse/helper/filterings/ParameterUtils.java
  server/juse/src/main/java/com/example/juse/helper/filterings/QueryParameters.java
  server/juse/src/main/java/com/example/juse/user/entity/User.java
  server/juse/src/main/resources/application-local.yaml
  server/juse/src/main/resources/application-plain.yaml
  server/juse/src/main/resources/db/mysql/data.sql
  server/juse/src/test/java/com/example/juse/helper/ParameterUtilsTest.java
Labels: feat, BE

#96 V2 hotfix (#83, #84, #85)
  server/juse/src/main/java/com/example/juse/board/controller/BoardController.java
  server/juse/src/main/java/com/example/juse/board/dto/BoardResponseDto.java
  server/juse/src/main/java/com/example/juse/board/entity/Board.java
  server/juse/src/main/java/com/example/juse/board/repository/BoardRepository.java
  server/juse/src/main/java/com/example/juse/helper/filterings/FilterOptions.java
  server/juse/src/main/java/com/example/juse/user/controller/UserTestController.java
  server/juse/src/main/java/com/example/juse/user/entity/User.java
  server/juse/src/main/java/com/example/juse/user/mapper/UserMapper.java
  server/juse/src/main/java/com/example/juse/user/service/UserServiceImpl.java
  server/juse/src/main/resources/db/mysql/data.sql
Labels: BE, fix

#101 V2 hotfix 88
  server/juse/.gitignore
  server/juse/src/main/java/com/example/juse/application/entity/Application.java
  server/juse/src/main/java/com/example/juse/application/service/ApplicationServiceImpl.java
  server/juse/src/main/java/com/example/juse/board/entity/Board.java
  server/juse/src/main/java/com/example/juse/bookmark/repository/BookmarkRepository.java
  server/juse/src/main/java/com/example/juse/bookmark/service/BookmarkServiceImpl.java
  server/juse/src/main/java/com/example/juse/security/config/SecurityConfig.java
  server/juse/src/main/java/com/example/juse/security/controller/TokenController.java
  server/juse/src/main/java/com/example/juse/security/handler/SuccessHandler.java
  server/juse/src/main/java/com/example/juse/user/entity/User.java
  server/juse/src/main/java/com/example/juse/user/mapper/UserMapper.java
  server/juse/src/main/java/com/example/juse/user/repository/UserRepository.java
  server/juse/src/main/java/com/example/juse/user/service/UserServiceImpl.java
  server/juse/src/main/resources/application-dev.yaml
  server/juse/src/main/resources/application-plain.yaml
  server/juse/src/main/resources/db/mysql/data.sql
Labels: BE, fix

#105 fix(question): 질문 작성 시 작성자 잘못기입되는 현상 해결 (#103)
  server/juse/src/main/java/com/example/juse/question/service/QuestionServiceImpl.java
Labels: bug, BE

#129 V2 backend feat #128
  client/src/assets/icons/bookmark.svg~merged
  server/juse/.gitignore
  server/juse/src/main/java/com/example/juse/application/controller/ApplicationController.java
  server/juse/src/main/java/com/example/juse/board/controller/BoardController.java
  server/juse/src/main/java/com/example/juse/board/dto/BoardRequestDto.java
  server/juse/src/main/java/com/example/juse/board/mapper/BoardMapper.java
  server/juse/src/main/java/com/example/juse/exception/BusinessLogicException.java
  server/juse/src/main/java/com/example/juse/exception/ExceptionCode.java
  server/juse/src/main/java/com/example/juse/user/controller/UserController.java
  server/juse/src/main/java/com/example/juse/user/dto/UserRequestDto.java
  server/juse/src/main/java/com/example/juse/user/mapper/UserMapper.java
  server/juse/src/main/java/com/example/juse/user/service/UserServiceImpl.java
  server/juse/src/main/resources/application-dev.yaml
  server/juse/src/main/resources/application-plain.yaml
Labels: BE, fix
